package jdkselector;

import java.awt.Cursor;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import org.openide.LifecycleManager;
import org.openide.awt.NotificationDisplayer;
import org.openide.util.Exceptions;
import org.openide.util.ImageUtilities;

final class JDKPanel extends javax.swing.JPanel {

	private final JDKOptionsPanelController controller;

	public PrintStream newStream;
	public ByteArrayOutputStream newConsole = new ByteArrayOutputStream();
	String jdkPath;
	String confFile = System.getProperty("netbeans.home").replace("platform", "")
			+ File.separator + "etc" + File.separator + "netbeans.conf";

	JDKPanel(JDKOptionsPanelController controller) {
		this.controller = controller;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jFrame1.setAlwaysOnTop(true);
        jFrame1.setBackground(java.awt.SystemColor.window);
        jFrame1.setMinimumSize(new java.awt.Dimension(550, 385));
        jFrame1.setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\Program Files\\Java"));
        jFileChooser1.setDialogTitle(org.openide.util.NbBundle.getMessage(JDKPanel.class, "JDKPanel.jFileChooser1.dialogTitle")); // NOI18N
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.setMinimumSize(new java.awt.Dimension(541, 360));
        jFileChooser1.setPreferredSize(new java.awt.Dimension(541, 360));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jPanel1.add(jFileChooser1, java.awt.BorderLayout.CENTER);

        jFrame1.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(JDKPanel.class, "JDKPanel.jLabel1.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(JDKPanel.class, "JDKPanel.jTextField1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(JDKPanel.class, "JDKPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(JDKPanel.class, "JDKPanel.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(43, 43, 43)
                .addComponent(jButton2)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		jFrame1.setVisible(true);
		jFileChooser1.setSelectedFile(new File(jdkPath));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
		// TODO add your handling code here:
		if (evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
			jdkPath = jFileChooser1.getSelectedFile().getPath();
			jTextField1.setText(jdkPath);
			jFrame1.dispose();
		} else {
			jFrame1.dispose();
		}

    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		try (BufferedReader reader = new BufferedReader(new FileReader(confFile))) {
			String line = null;
			newConsole.reset();
			newStream = new PrintStream(newConsole);
			System.setOut(newStream);

			while ((line = reader.readLine()) != null) {
				if (line.startsWith("netbeans_jdkhome")) {
					line = line.replace(line, "netbeans_jdkhome=\"" + jdkPath + "\"");
					System.out.println(line);
				} else {
					System.out.println(line);
				}
			}
			newStream.flush();
			try (PrintWriter writer = new PrintWriter(new FileWriter(confFile))) {
				writer.append(newConsole.toString().trim());

				JLabel clickable = new JLabel("<html><a href=\"\">Restart Netbeans</a></html>");
				clickable.setCursor(new Cursor(Cursor.HAND_CURSOR));
				clickable.addMouseListener(new MouseListener() {
					@Override
					public void mouseClicked(MouseEvent e) {
						LifecycleManager.getDefault().markForRestart();
						LifecycleManager.getDefault().exit();
					}

					@Override
					public void mousePressed(MouseEvent e) {
					}

					@Override
					public void mouseReleased(MouseEvent e) {
					}

					@Override
					public void mouseEntered(MouseEvent e) {
					}

					@Override
					public void mouseExited(MouseEvent e) {
					}

				});

				NotificationDisplayer.getDefault().notify("Restart to Apply JDK Change",
						ImageUtilities.loadImageIcon("jdkselector/icons8-refresh-16.png", true),
						clickable,
						clickable, NotificationDisplayer.Priority.NORMAL, NotificationDisplayer.Category.INFO);

			}
		} catch (IOException ex) {
			Exceptions.printStackTrace(ex);
		}
    }//GEN-LAST:event_jButton2ActionPerformed

	void load() throws IOException {
		try (BufferedReader reader = new BufferedReader(new FileReader(confFile))) {
			String line = null;
			newConsole.reset();
			newStream = new PrintStream(newConsole);
			System.setOut(newStream);

			while ((line = reader.readLine()) != null) {
				if (line.startsWith("netbeans_jdkhome")) {
					jdkPath = line.split("netbeans_jdkhome=")[1].replace("\"", "");
					jTextField1.setText(jdkPath);
					break;
				}
			}
		}
	}

	void store() {
	}

	boolean valid() {
		return true;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
